"""add r2_key field to knowledge_docs

Revision ID: 631f31ba6f26
Revises:
Create Date: 2026-01-18 23:21:56.850251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers
revision = '631f31ba6f26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_docs', sa.Column('r2_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_docs', 'r2_key')
    # ### end Alembic commands ###